### ISSUE TITLE
“สารานุกรม ไทย|สำหรับ เยาวชน ฯ    ”  got error

### ISSUE THREAD

**Issue by peter05010402** [PyThaiNLP/tts-thai#7]

**Comment by wannaphongcom** [comment]
Can you identify more problems?

**Comment by peter05010402** [comment]
you can try it:"สารานุกรม ไทย|สำหรับ เยาวชน ฯ "

**Comment by wannaphongcom** [comment]
try "สารานุกรม ไทย สำหรับ เยาวชน". This project wants word tokenization.

**Comment by peter05010402** [comment]
Thank you！
